name: fox_iot
description: Project for IoT manipulation

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.0
  get_it: ^7.6.4
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0

provider:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/res/assets/logo1.png
    - lib/res/assets/icon_facebook.png
    - lib/res/assets/visible_icon.png
    - lib/res/assets/person_icon.png
    - lib/res/assets/lock_passw_icon.png
    - lib/res/assets/e_mail_icon.png
