name: fox_iot
description: Project for IoT manipulation

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.0
  get_it: ^7.6.4
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.0
  flutter_blue: ^0.8.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.0.0
  http: ^1.1.1
  oauth2_client: ^3.2.2
  crypto: ^3.0.1

provider:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/res/assets/logo1.png
    - lib/res/assets/icon_facebook.png
    - lib/res/assets/visible_icon.png
    - lib/res/assets/person_icon.png
    - lib/res/assets/lock_passw_icon.png
    - lib/res/assets/e_mail_icon.png
    - lib/res/assets/account_s.png
    - lib/res/assets/devices_s.png
    - lib/res/assets/home_s.png
    - lib/res/assets/rules_s.png
    - lib/res/assets/account_un.png
    - lib/res/assets/devices_un.png
    - lib/res/assets/home_un.png
    - lib/res/assets/rules_un.png
    - lib/res/assets/add_device.png
    - lib/res/assets/undefined.png
    - lib/res/assets/hub.png
    - lib/res/assets/bulb.png
    - lib/res/assets/error_search.png
    - lib/res/assets/bluetooth.png
    - lib/res/assets/active_devices.png
    - lib/res/assets/family_members.png
    - lib/res/assets/settings.png
    - lib/res/assets/support.png
    - lib/res/assets/exit.png
    - lib/res/assets/family.png
    - lib/res/assets/next_arrow.png
