// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl3Pn1bo2kRRrQP5rFZcGeVFVKTRbD45A',
    appId: '1:280060386093:web:ff8039067fd0390c1551a4',
    messagingSenderId: '280060386093',
    projectId: 'foxiot-c2a76',
    authDomain: 'foxiot-c2a76.firebaseapp.com',
    storageBucket: 'foxiot-c2a76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDskclhZyvhNQ57t2mQ5dYPbJDNbbt-Qcg',
    appId: '1:280060386093:android:05b6f61ff948b98b1551a4',
    messagingSenderId: '280060386093',
    projectId: 'foxiot-c2a76',
    storageBucket: 'foxiot-c2a76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDizFIlloc-4L5xk6qAtysKaiFSmEBfJ7Y',
    appId: '1:280060386093:ios:057484c7859a44531551a4',
    messagingSenderId: '280060386093',
    projectId: 'foxiot-c2a76',
    storageBucket: 'foxiot-c2a76.appspot.com',
    iosBundleId: 'com.example.foxIot',
  );
}
